"""Public surface for the Phase 1 Methodology Kernel contract."""

from .api import MethodologyKernel
from .brain import BrainIntegrityError, BrainManifest, load_brain_manifest
from .contracts import (
    AnalysisRequest,
    AnalysisResultEnvelope,
    AnalyzedWaveSubject,
    CertifiedStructuralInvalidity,
    CertifiedValidatedInternalFamily,
    InternalFamilyKind,
    InternalFamilyValidatorResult,
    KernelStatus,
    NormalImpulseFiveSlotCandidateView,
    NormalImpulseFiveSlotCardinalityError,
    OrderedChildBinding,
    StructuralInvalidityCertificationError,
    StructuralValidatorResult,
    SubjectBoundObservedPriceEndpointPair,
    SubjectBoundObservedPriceObservation,
    ValidatedInternalFamilyCertificationError,
    certify_validated_internal_family,
    certify_structural_invalidity,
)
from .degree_peer_consistency import (
    DegreePeerCheckStatus,
    DegreePeerConsistencyInput,
    DegreePeerConsistencyResult,
    DegreePeerExecutionRole,
    check_degree_peer_consistency,
)
from .ending_diagonal_cardinality import (
    EndingDiagonalCandidateScope,
    EndingDiagonalCardinalityInput,
    EndingDiagonalCardinalityResult,
    EndingDiagonalCardinalityStatus,
    EndingDiagonalExecutionRole,
    check_ending_diagonal_cardinality,
)
from .p004 import (
    CandidateScope,
    ExecutionRole,
    ImpulseDirection,
    P004Input,
    P004Result,
    RuleCheckStatus,
    check_p004,
)
from .p023_visibility_guard import (
    P023VisibilityCheckStatus,
    P023VisibilityExecutionRole,
    P023VisibilityInput,
    P023VisibilityResult,
    P023VisibilityState,
    check_p023_visibility_guard,
)
from .parent_child_degree_adjacency import (
    ParentChildDegreeCheckStatus,
    ParentChildDegreeExecutionRole,
    ParentChildDegreeInput,
    ParentChildDegreeResult,
    check_parent_child_degree_adjacency,
)
from .p007_single_zigzag_cardinality import (
    P007CandidateScope,
    P007CardinalityStatus,
    P007ExecutionRole,
    P007SingleZigzagCardinalityInput,
    P007SingleZigzagCardinalityResult,
    check_p007_single_zigzag_cardinality,
)
from .p008_flat_cardinality import (
    P008CandidateScope,
    P008CardinalityStatus,
    P008ExecutionRole,
    P008FlatCardinalityInput,
    P008FlatCardinalityResult,
    check_p008_flat_cardinality,
)
from .p009_triangle_cardinality import (
    P009CandidateScope,
    P009CardinalityStatus,
    P009ExecutionRole,
    P009TriangleCardinalityInput,
    P009TriangleCardinalityResult,
    check_p009_triangle_cardinality,
)
from ._structural_invalidity_certification import (
    _seal_structural_validator_registry,
)
from ._validated_internal_family_certification import (
    _seal_internal_family_validator_registry,
)


_seal_structural_validator_registry(
    expected_result_types=(
        P004Result,
        DegreePeerConsistencyResult,
        ParentChildDegreeResult,
        P007SingleZigzagCardinalityResult,
        P008FlatCardinalityResult,
        P009TriangleCardinalityResult,
        EndingDiagonalCardinalityResult,
    )
)
del _seal_structural_validator_registry

_seal_internal_family_validator_registry(expected_result_types=())
del _seal_internal_family_validator_registry

from .structural_invalidity_evidence_no_rescue import (
    StructuralInvalidityEvidenceNoRescueExecutionRole,
    StructuralInvalidityEvidenceNoRescuePolicyStatus,
    StructuralInvalidityEvidenceNoRescueResult,
    apply_structural_invalidity_evidence_no_rescue,
)
from .p003_one_larger_degree_theme import (
    P003ExecutionRole,
    P003OneLargerDegreeRelation,
    P003OneLargerDegreeThemeInput,
    P003OneLargerDegreeThemeResult,
    P003SearchTheme,
    P003ThemeMappingStatus,
    map_p003_one_larger_degree_theme,
)
from .bounded_recursive_analysis import (
    ARTIFACT_CLASSIFICATION,
    OPERATIONAL_POLICY_CLASSIFICATION,
    AnalysisResolutionState,
    BoundedRecursiveAnalysisContractError,
    BoundedRecursiveAnalysisNode,
    BoundedRecursiveAnalysisResolution,
    MethodologyDependencyCode,
    OperationalAggregationState,
    SubjectBoundP023VisibilityResult,
    aggregate_supplied_child_resolutions,
    evaluate_p023_visibility_for_subject,
)
from .candidate_analysis_envelope import (
    CandidateAnalysisEnvelope,
    CandidateAnalysisEnvelopeError,
    CandidateMethodologyEvaluation,
    CandidateObservationAttachment,
)
from .single_candidate_orchestration import (
    CandidateBehaviorExecution,
    CandidateEvaluationPresence,
    SingleCandidateAnalysisRequest,
    SingleCandidateAnalysisResult,
    SingleCandidateExecutionSummary,
    SingleCandidateOrchestrationError,
)
from .explicit_behavior_execution import (
    ExplicitBehaviorExecutionError,
    ExplicitBehaviorExecutionRecord,
    ExplicitBehaviorExecutionRequest,
    ExplicitBehaviorExecutionResult,
    ExplicitBehaviorExecutionState,
    ExplicitBehaviorInput,
)
from .manual_structure_candidate_builder import (
    CALLER_SUPPLIED_STRUCTURAL_FACT,
    ManualCardinalityBehavior,
    ManualDegreePeerFact,
    ManualDirectChildCardinalityFact,
    ManualP003OneLargerDegreeRelationFact,
    ManualP004Wave2OriginFact,
    ManualP023VisibilityFact,
    ManualParentChildDegreeFact,
    ManualStructureCandidateBuildResult,
    ManualStructureCandidateBuilderError,
    ManualStructureCandidateRequest,
)

__all__ = [
    "AnalysisRequest",
    "AnalysisResultEnvelope",
    "AnalysisResolutionState",
    "AnalyzedWaveSubject",
    "ARTIFACT_CLASSIFICATION",
    "BrainIntegrityError",
    "BrainManifest",
    "BoundedRecursiveAnalysisContractError",
    "BoundedRecursiveAnalysisNode",
    "BoundedRecursiveAnalysisResolution",
    "CandidateScope",
    "CALLER_SUPPLIED_STRUCTURAL_FACT",
    "CandidateAnalysisEnvelope",
    "CandidateAnalysisEnvelopeError",
    "CandidateMethodologyEvaluation",
    "CandidateObservationAttachment",
    "CandidateBehaviorExecution",
    "CandidateEvaluationPresence",
    "CertifiedStructuralInvalidity",
    "CertifiedValidatedInternalFamily",
    "DegreePeerCheckStatus",
    "DegreePeerConsistencyInput",
    "DegreePeerConsistencyResult",
    "DegreePeerExecutionRole",
    "ExecutionRole",
    "ExplicitBehaviorExecutionError",
    "ExplicitBehaviorExecutionRecord",
    "ExplicitBehaviorExecutionRequest",
    "ExplicitBehaviorExecutionResult",
    "ExplicitBehaviorExecutionState",
    "ExplicitBehaviorInput",
    "EndingDiagonalCandidateScope",
    "EndingDiagonalCardinalityInput",
    "EndingDiagonalCardinalityResult",
    "EndingDiagonalCardinalityStatus",
    "EndingDiagonalExecutionRole",
    "ImpulseDirection",
    "InternalFamilyKind",
    "InternalFamilyValidatorResult",
    "KernelStatus",
    "ManualCardinalityBehavior",
    "ManualDegreePeerFact",
    "ManualDirectChildCardinalityFact",
    "ManualP003OneLargerDegreeRelationFact",
    "ManualP004Wave2OriginFact",
    "ManualP023VisibilityFact",
    "ManualParentChildDegreeFact",
    "ManualStructureCandidateBuildResult",
    "ManualStructureCandidateBuilderError",
    "ManualStructureCandidateRequest",
    "MethodologyKernel",
    "MethodologyDependencyCode",
    "NormalImpulseFiveSlotCandidateView",
    "NormalImpulseFiveSlotCardinalityError",
    "OPERATIONAL_POLICY_CLASSIFICATION",
    "OperationalAggregationState",
    "OrderedChildBinding",
    "P003ExecutionRole",
    "P003OneLargerDegreeRelation",
    "P003OneLargerDegreeThemeInput",
    "P003OneLargerDegreeThemeResult",
    "P003SearchTheme",
    "P003ThemeMappingStatus",
    "P004Input",
    "P004Result",
    "P007CandidateScope",
    "P007CardinalityStatus",
    "P007ExecutionRole",
    "P007SingleZigzagCardinalityInput",
    "P007SingleZigzagCardinalityResult",
    "P008CandidateScope",
    "P008CardinalityStatus",
    "P008ExecutionRole",
    "P008FlatCardinalityInput",
    "P008FlatCardinalityResult",
    "P009CandidateScope",
    "P009CardinalityStatus",
    "P009ExecutionRole",
    "P009TriangleCardinalityInput",
    "P009TriangleCardinalityResult",
    "P023VisibilityCheckStatus",
    "P023VisibilityExecutionRole",
    "P023VisibilityInput",
    "P023VisibilityResult",
    "P023VisibilityState",
    "ParentChildDegreeCheckStatus",
    "ParentChildDegreeExecutionRole",
    "ParentChildDegreeInput",
    "ParentChildDegreeResult",
    "RuleCheckStatus",
    "SingleCandidateAnalysisRequest",
    "SingleCandidateAnalysisResult",
    "SingleCandidateExecutionSummary",
    "SingleCandidateOrchestrationError",
    "StructuralInvalidityCertificationError",
    "StructuralInvalidityEvidenceNoRescueExecutionRole",
    "StructuralInvalidityEvidenceNoRescuePolicyStatus",
    "StructuralInvalidityEvidenceNoRescueResult",
    "StructuralValidatorResult",
    "SubjectBoundObservedPriceEndpointPair",
    "SubjectBoundObservedPriceObservation",
    "SubjectBoundP023VisibilityResult",
    "ValidatedInternalFamilyCertificationError",
    "apply_structural_invalidity_evidence_no_rescue",
    "aggregate_supplied_child_resolutions",
    "check_degree_peer_consistency",
    "check_ending_diagonal_cardinality",
    "check_p023_visibility_guard",
    "check_parent_child_degree_adjacency",
    "check_p004",
    "check_p007_single_zigzag_cardinality",
    "check_p008_flat_cardinality",
    "check_p009_triangle_cardinality",
    "certify_structural_invalidity",
    "certify_validated_internal_family",
    "evaluate_p023_visibility_for_subject",
    "load_brain_manifest",
    "map_p003_one_larger_degree_theme",
]
